<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_DisabledIn ServiceTemporary Out of Service</name>
   <tag></tag>
   <elementGuidId>8e2629cf-5bc4-4663-873e-8f19db8a54ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Active']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f1a687d2-36e9-432f-8c60-09193c473c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Active</value>
      <webElementGuid>02e14e1d-b4ef-42c5-8369-05343b6018f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Active</value>
      <webElementGuid>d91a8845-68a8-4959-ba25-24d4afbf2e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selection-input form-control</value>
      <webElementGuid>1ae95139-0bb5-46bb-a835-0fdf8bc3fb02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DisabledIn ServiceTemporary Out of Service</value>
      <webElementGuid>84c7b211-4bb5-4e2c-80c0-7cc90cad9a7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Active&quot;)</value>
      <webElementGuid>5d744e3b-36c6-4ec6-a109-4f030baadfd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Active']</value>
      <webElementGuid>fbbda969-48c7-4ce7-baf3-3ea175d02efc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div[2]/div[2]/div[3]/div[2]/select</value>
      <webElementGuid>9efba219-1260-40b0-a2fd-32e3bc5715f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active :'])[1]/following::select[1]</value>
      <webElementGuid>efc75537-314e-472c-a468-8d3cb3ff6511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Online Hours'])[2]/following::select[1]</value>
      <webElementGuid>809e6f46-b7b4-4b89-b2b9-12c5115a3081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal Details'])[1]/preceding::select[1]</value>
      <webElementGuid>95d516c7-72ba-4124-9200-310c313f097a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>1bdcb9c3-e09f-4058-ae28-a935a8766227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Active' and @name = 'Active' and (text() = 'DisabledIn ServiceTemporary Out of Service' or . = 'DisabledIn ServiceTemporary Out of Service')]</value>
      <webElementGuid>373baa92-ac6d-4963-85ae-9b34a334c91b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
