<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AreaAmpanganBahauBandar Baru Serting_fae656</name>
   <tag></tag>
   <elementGuidId>a41c2c8d-63a0-4bdd-bf13-8b793bd194e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Area']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Area</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b281241a-83f1-411e-87cd-e82e1ceeebeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Area</value>
      <webElementGuid>85d5bf65-c430-4282-a094-f58daba15690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Area</value>
      <webElementGuid>29e1542b-2d20-4c3b-bdea-132b55070c46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selection-input form-control</value>
      <webElementGuid>ac33aaaf-3f21-44f7-a103-123b65e12af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AreaAmpanganBahauBandar Baru SertingBandar EnstekBandar Sri SendayanBatang MelakaBatu KikirBukit KepayangGemasGemenchehJelebuJempolJimahJoholJuassehKotaKuala KlawangKuala PilahLabuLenggengLinggiLukutMantinNilaiPantaiParoiPasir PanjangPedasPort DicksonRantauRasahRembauRompinSenawangSerembanSeremban 2SikamatSiliauSimpang DurianSimpang PertangSri MenantiSri RusaTampinTanjong IpohTelok KemangTiti</value>
      <webElementGuid>2167451a-cace-44d1-a995-62610cf5b34c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Area&quot;)</value>
      <webElementGuid>dd9e813f-5413-4b09-9df3-d6a2f4bc006a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Area']</value>
      <webElementGuid>be66e00b-018b-4c58-b015-1f0da403d82b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div[2]/div[2]/div[4]/div/div[13]/div[3]/select</value>
      <webElementGuid>fc801170-0d10-49ff-b25b-191aa9b9fde4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Area :'])[1]/following::select[1]</value>
      <webElementGuid>a0bd94e1-d0d2-496a-82bf-fe44c0486bbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State :'])[1]/following::select[2]</value>
      <webElementGuid>5b296a33-e4d6-4fef-81b0-5b75680702e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About :'])[1]/preceding::select[1]</value>
      <webElementGuid>b0858a82-5206-453f-850e-669b27bb1400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Maximum Length = 250 characters)'])[1]/preceding::select[1]</value>
      <webElementGuid>71ccfe01-e071-4588-a689-917f96aee08f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>9747963a-fdf6-449c-b7d7-7f0bec9915bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Area' and @name = 'Area' and (text() = 'AreaAmpanganBahauBandar Baru SertingBandar EnstekBandar Sri SendayanBatang MelakaBatu KikirBukit KepayangGemasGemenchehJelebuJempolJimahJoholJuassehKotaKuala KlawangKuala PilahLabuLenggengLinggiLukutMantinNilaiPantaiParoiPasir PanjangPedasPort DicksonRantauRasahRembauRompinSenawangSerembanSeremban 2SikamatSiliauSimpang DurianSimpang PertangSri MenantiSri RusaTampinTanjong IpohTelok KemangTiti' or . = 'AreaAmpanganBahauBandar Baru SertingBandar EnstekBandar Sri SendayanBatang MelakaBatu KikirBukit KepayangGemasGemenchehJelebuJempolJimahJoholJuassehKotaKuala KlawangKuala PilahLabuLenggengLinggiLukutMantinNilaiPantaiParoiPasir PanjangPedasPort DicksonRantauRasahRembauRompinSenawangSerembanSeremban 2SikamatSiliauSimpang DurianSimpang PertangSri MenantiSri RusaTampinTanjong IpohTelok KemangTiti')]</value>
      <webElementGuid>cadb8cce-22a1-4a42-80ec-215523ff1e79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
