<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_StateJohorKedahKelantanMelakaNegeri _ee4b0a</name>
   <tag></tag>
   <elementGuidId>1c2c9296-92c7-4f20-b183-1af391a711ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='State']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#State</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5312f84b-3067-4b48-8de6-d9174d789289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>State</value>
      <webElementGuid>9e8a2cf1-7422-4bc3-bca9-2f841d3a5ae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>State</value>
      <webElementGuid>02759fe0-6277-4415-8baa-8029e3419cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selection-input form-control</value>
      <webElementGuid>b5f790f1-677e-4ea2-8550-616960613625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>StateJohorKedahKelantanMelakaNegeri SembilanPahangPenangPerakPerlisSabahSarawakSelangorTerengganuWilayah Persekutuan Kuala LumpurWilayah Persekutuan LabuanWilayah Persekutuan Putrajaya</value>
      <webElementGuid>68338eca-777c-4871-a0d6-8e9b78102656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;State&quot;)</value>
      <webElementGuid>232e5ffe-df0e-4182-a45b-8fb2e62e0996</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='State']</value>
      <webElementGuid>fb16e087-a17d-45c4-bcac-111bdc874c60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div[2]/div[2]/div[4]/div/div[13]/div[2]/select</value>
      <webElementGuid>c48abb10-23bb-43ab-987b-f9e8eee04df9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State :'])[1]/following::select[1]</value>
      <webElementGuid>0abafc19-fa5d-4ebd-a07a-c532c983d416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kuchai Lama'])[1]/following::select[1]</value>
      <webElementGuid>7f30c8cc-cbba-43fc-8b95-ee255cfb2457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Area :'])[1]/preceding::select[1]</value>
      <webElementGuid>e6a6fbcb-9c37-4026-8d13-26efbc598358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About :'])[1]/preceding::select[2]</value>
      <webElementGuid>589780fe-342d-4347-9261-970fc296438e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div[2]/select</value>
      <webElementGuid>b196b9a8-3578-45c6-9196-4798d6f0e2d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'State' and @name = 'State' and (text() = 'StateJohorKedahKelantanMelakaNegeri SembilanPahangPenangPerakPerlisSabahSarawakSelangorTerengganuWilayah Persekutuan Kuala LumpurWilayah Persekutuan LabuanWilayah Persekutuan Putrajaya' or . = 'StateJohorKedahKelantanMelakaNegeri SembilanPahangPenangPerakPerlisSabahSarawakSelangorTerengganuWilayah Persekutuan Kuala LumpurWilayah Persekutuan LabuanWilayah Persekutuan Putrajaya')]</value>
      <webElementGuid>58b23094-49b3-4bee-be69-7d40881e1e67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
