<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_GenderFemaleMale</name>
   <tag></tag>
   <elementGuidId>3044afce-f840-459f-8f69-a380b96221dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Gender']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Gender</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8d3291d0-be27-4bcb-b40a-96cf037269a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Gender</value>
      <webElementGuid>f5254009-c658-4702-8d93-84443eb84567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Gender</value>
      <webElementGuid>c7c6ec52-c9cd-4fc6-996b-a20081ed7cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selection-input form-control</value>
      <webElementGuid>ac815e67-bd72-4545-9787-7f739dc1f980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GenderFemaleMale</value>
      <webElementGuid>3cc52863-8de2-4679-9ebb-a68d3f40d1eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Gender&quot;)</value>
      <webElementGuid>48a877e2-1fb0-4800-80ba-7c5a05630b69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Gender']</value>
      <webElementGuid>96d9d27b-0db2-454c-9fde-c8275028136a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div[2]/div[2]/div[4]/div/div[11]/div[2]/select</value>
      <webElementGuid>6c34d435-bed4-45f7-9ec2-29190a6bcc6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gender :'])[1]/following::select[1]</value>
      <webElementGuid>235d4c6d-efc5-4aff-8c0b-1adbcbd60293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date of Birth :'])[1]/following::select[1]</value>
      <webElementGuid>dd9f6669-d9fa-4a09-a8a3-6dcbe4f36ba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address :'])[1]/preceding::select[1]</value>
      <webElementGuid>3a902e33-7d7a-4abf-a1c1-0ec78cd6f23f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State :'])[1]/preceding::select[1]</value>
      <webElementGuid>d1466fa3-0103-4091-88a9-cd3b121307e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div[2]/select</value>
      <webElementGuid>bcf96280-3b67-4be8-86b4-c425dda75942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Gender' and @name = 'Gender' and (text() = 'GenderFemaleMale' or . = 'GenderFemaleMale')]</value>
      <webElementGuid>bdd508a7-47a0-4086-ba2e-d00ed72f971b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
