<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_agents</name>
   <tag></tag>
   <elementGuidId>103d564f-6702-4c7a-a628-23e9d57ef886</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;navItem-agents-0&quot;)/span[2][count(. | //span[(text() = 'agents' or . = 'agents')]) = count(//span[(text() = 'agents' or . = 'agents')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>285a6731-e323-4444-9f18-eb2de7034d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>agents</value>
      <webElementGuid>3f7a6e6c-f5d0-42a8-a843-e1f7df2edf8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navItem-agents-0&quot;)/span[2]</value>
      <webElementGuid>e26a8ef5-d078-4248-a446-69fcb8128ba6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='navItem-agents-0']/span[2]</value>
      <webElementGuid>ac138cfd-5d7f-4e24-8bed-44fe18ef8247</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='agency'])[1]/following::span[2]</value>
      <webElementGuid>46cc9f03-cfad-469e-94a4-6edea1fcc6a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Area Master'])[1]/following::span[3]</value>
      <webElementGuid>bee13769-945d-41fa-bf8f-5364c30a25e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='agent application'])[1]/preceding::span[2]</value>
      <webElementGuid>9a3ec39c-eea5-4496-8ec4-d55c9a5ba890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='properties'])[1]/preceding::span[4]</value>
      <webElementGuid>2cce785e-d042-4144-8bf8-b45ffb772fe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='agents']/parent::*</value>
      <webElementGuid>29b4a468-f9d2-4173-8742-061da6f3c0c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/li/a/span[2]</value>
      <webElementGuid>df1e9052-7146-43c3-9611-fe0f1cf0b333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'agents' or . = 'agents')]</value>
      <webElementGuid>68293935-177a-4271-9f22-131469d3c351</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
