<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AreaAmpanganBahauBandar Baru Serting_fae656</name>
   <tag></tag>
   <elementGuidId>94da4d7d-e876-46c5-8e3d-aeb681f75200</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Area</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Area']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>21cf89f6-ad52-40ad-99cb-0fc89865afe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f92ccf29-5307-47af-b794-99bd1d22fc82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Area</value>
      <webElementGuid>628e90e5-d093-474e-b69d-192befde9529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Area</value>
      <webElementGuid>d0060a37-856b-48aa-9d05-ed604f89bb65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AreaAmpanganBahauBandar Baru SertingBandar EnstekBandar Sri SendayanBatang MelakaBatu KikirBukit KepayangGemasGemenchehJelebuJempolJimahJoholJuassehKotaKuala KlawangKuala PilahLabuLenggengLinggiLukutMantinNilaiPantaiParoiPasir PanjangPedasPort DicksonRantauRasahRembauRompinSenawangSerembanSeremban 2SikamatSiliauSimpang DurianSimpang PertangSri MenantiSri RusaTampinTanjong IpohTelok KemangTiti</value>
      <webElementGuid>7b8d0446-62cb-468b-ae2f-122571f6e517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Area&quot;)</value>
      <webElementGuid>6429cd6a-0295-4211-b963-2dc117d9ad4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2cd85a49-2d30-4cc2-8e50-eeafb0825804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>38e6ba4f-2115-49aa-ba18-28f5ab7106f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Area</value>
      <webElementGuid>62965b99-0187-4748-8687-7bce6f09f836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Area</value>
      <webElementGuid>de742494-e872-415a-b141-25b4ff2b255d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AreaAmpanganBahauBandar Baru SertingBandar EnstekBandar Sri SendayanBatang MelakaBatu KikirBukit KepayangGemasGemenchehJelebuJempolJimahJoholJuassehKotaKuala KlawangKuala PilahLabuLenggengLinggiLukutMantinNilaiPantaiParoiPasir PanjangPedasPort DicksonRantauRasahRembauRompinSenawangSerembanSeremban 2SikamatSiliauSimpang DurianSimpang PertangSri MenantiSri RusaTampinTanjong IpohTelok KemangTiti</value>
      <webElementGuid>17807d6b-8c7b-46f7-9d85-ce909e7b8ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Area&quot;)</value>
      <webElementGuid>e6f852bd-df26-4d7c-b811-0469329d412e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8c78f5f3-0a54-4f09-96ac-97410603af1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e22c1a0e-8240-4f05-aa82-7ed71cc78758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Area</value>
      <webElementGuid>6a2c7186-e92c-4612-9856-dee1b7008c97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Area</value>
      <webElementGuid>2c495731-3f82-4d75-98b2-6cc40cb0980b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AreaAmpanganBahauBandar Baru SertingBandar EnstekBandar Sri SendayanBatang MelakaBatu KikirBukit KepayangGemasGemenchehJelebuJempolJimahJoholJuassehKotaKuala KlawangKuala PilahLabuLenggengLinggiLukutMantinNilaiPantaiParoiPasir PanjangPedasPort DicksonRantauRasahRembauRompinSenawangSerembanSeremban 2SikamatSiliauSimpang DurianSimpang PertangSri MenantiSri RusaTampinTanjong IpohTelok KemangTiti</value>
      <webElementGuid>b21b6a29-c88b-40a9-9fbb-96d3f46f6f27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Area&quot;)</value>
      <webElementGuid>0c8ced2c-b182-40fa-8112-8275e7463246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5c0b3038-e282-4b19-8f74-3956d2678444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>cbcb2499-9098-42db-8142-f1d3591cdaf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Area</value>
      <webElementGuid>7463ed7b-8712-40c9-b7bf-9bdfe58c262d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Area</value>
      <webElementGuid>a01c79a9-6be3-4b16-a2cc-72278f232c1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AreaAmpanganBahauBandar Baru SertingBandar EnstekBandar Sri SendayanBatang MelakaBatu KikirBukit KepayangGemasGemenchehJelebuJempolJimahJoholJuassehKotaKuala KlawangKuala PilahLabuLenggengLinggiLukutMantinNilaiPantaiParoiPasir PanjangPedasPort DicksonRantauRasahRembauRompinSenawangSerembanSeremban 2SikamatSiliauSimpang DurianSimpang PertangSri MenantiSri RusaTampinTanjong IpohTelok KemangTiti</value>
      <webElementGuid>652291fd-02ad-4abd-b35e-974e43bacbca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Area&quot;)</value>
      <webElementGuid>5566da3d-790b-4d4b-a6ea-82ff52d580ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Area']</value>
      <webElementGuid>f1e64a60-1acc-4277-9d95-42b97e86f61f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div[2]/div/div[2]/div[4]/div[3]/select</value>
      <webElementGuid>8f756d81-5b56-4760-a4cf-e218118e8164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Property Address'])[1]/following::select[3]</value>
      <webElementGuid>8ee9f181-aa62-430b-9977-e07234e02c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address Section'])[1]/following::select[3]</value>
      <webElementGuid>526fae01-03a6-4685-b883-e7695f9b71c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='auto refresh/generated when saved'])[1]/preceding::select[1]</value>
      <webElementGuid>469d2fae-5e9b-4a7d-8fbf-5d3bedb7cfc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save and Next'])[1]/preceding::select[1]</value>
      <webElementGuid>25feb21b-9885-4582-8f44-c68b5fb8de97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/select</value>
      <webElementGuid>0cc974d3-5833-41f5-8e05-406a7da1756f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Area' and @name = 'Area' and (text() = 'AreaAmpanganBahauBandar Baru SertingBandar EnstekBandar Sri SendayanBatang MelakaBatu KikirBukit KepayangGemasGemenchehJelebuJempolJimahJoholJuassehKotaKuala KlawangKuala PilahLabuLenggengLinggiLukutMantinNilaiPantaiParoiPasir PanjangPedasPort DicksonRantauRasahRembauRompinSenawangSerembanSeremban 2SikamatSiliauSimpang DurianSimpang PertangSri MenantiSri RusaTampinTanjong IpohTelok KemangTiti' or . = 'AreaAmpanganBahauBandar Baru SertingBandar EnstekBandar Sri SendayanBatang MelakaBatu KikirBukit KepayangGemasGemenchehJelebuJempolJimahJoholJuassehKotaKuala KlawangKuala PilahLabuLenggengLinggiLukutMantinNilaiPantaiParoiPasir PanjangPedasPort DicksonRantauRasahRembauRompinSenawangSerembanSeremban 2SikamatSiliauSimpang DurianSimpang PertangSri MenantiSri RusaTampinTanjong IpohTelok KemangTiti')]</value>
      <webElementGuid>799aed95-64c6-473d-9dbf-daa185dc9647</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
