<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_StateJohorKedahKelantanMelakaNegeri _ee4b0a</name>
   <tag></tag>
   <elementGuidId>ddb701f5-ade9-449a-9597-86eb8dac6c4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#State</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='State']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f998d41b-90f9-4033-901f-69c9a1b048f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>State</value>
      <webElementGuid>78f84cf3-1bd4-40b1-a99a-09b5f65597f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>State</value>
      <webElementGuid>fea8d537-f257-4641-81a2-429c617c6847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selection-input form-control</value>
      <webElementGuid>9aa2e3a8-cc85-4c04-b0f6-a1c45b3b58f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>StateJohorKedahKelantanMelakaNegeri SembilanPahangPenangPerakPerlisSabahSarawakSelangorTerengganuWilayah Persekutuan Kuala LumpurWilayah Persekutuan LabuanWilayah Persekutuan Putrajaya</value>
      <webElementGuid>db419c8f-4fc7-46a9-b924-6d40ddd34e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;State&quot;)</value>
      <webElementGuid>4ed31ea4-963f-4b27-a9d1-2ffb96d58f5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='State']</value>
      <webElementGuid>dfd3ef2b-a283-4859-83ab-14fb62cf7d31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div[2]/div/div[2]/div[11]/div[5]/div[2]/select</value>
      <webElementGuid>d135cc8e-7a2e-4acc-8cce-aefa60813983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[12]/following::select[1]</value>
      <webElementGuid>a2046c8d-0093-458f-bdde-3ea49617777f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[13]/preceding::select[1]</value>
      <webElementGuid>ef0b14ab-4d32-4643-9cfc-2832699f36f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/select</value>
      <webElementGuid>adf16648-489c-448f-ab85-7a0c7b8c3358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'State' and @name = 'State' and (text() = 'StateJohorKedahKelantanMelakaNegeri SembilanPahangPenangPerakPerlisSabahSarawakSelangorTerengganuWilayah Persekutuan Kuala LumpurWilayah Persekutuan LabuanWilayah Persekutuan Putrajaya' or . = 'StateJohorKedahKelantanMelakaNegeri SembilanPahangPenangPerakPerlisSabahSarawakSelangorTerengganuWilayah Persekutuan Kuala LumpurWilayah Persekutuan LabuanWilayah Persekutuan Putrajaya')]</value>
      <webElementGuid>07bbdbfe-cd32-495f-ad28-88d5b26f2867</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
